"""first

Revision ID: c9329baae59f
Revises: 
Create Date: 2021-09-22 12:09:11.939265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9329baae59f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_name'), 'wish', ['name'], unique=False)
    op.create_index(op.f('ix_wish_url'), 'wish', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wish_url'), table_name='wish')
    op.drop_index(op.f('ix_wish_name'), table_name='wish')
    op.drop_table('wish')
    # ### end Alembic commands ###
